config/routes.rb
Rails.application.routes.draw do
  resources :leaverequests
  get 'users/index'
  resources :clockeds
  resources :uprofiles
  root 'dashboard#index'
  resources :clocks
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/uprofile.rb
class Uprofile < ApplicationRecord
  belongs_to :user
   has_many :leaverequests, dependent: :destroy
end

app/controllers/uprofiles_controller.rb
class UprofilesController < ApplicationController
  before_action :set_uprofile, only: [:show, :edit, :update, :destroy]

  # GET /uprofiles
  # GET /uprofiles.json
  def index
    @uprofiles = Uprofile.all
  end

  # GET /uprofiles/1
  # GET /uprofiles/1.json
  def show
  end

  # GET /uprofiles/new
  def new
    @uprofile = Uprofile.new
  end
  
  # GET /uprofiles/1/edit
  def edit
  end

  # POST /uprofiles
  # POST /uprofiles.json
  def create
    @uprofile = Uprofile.new(uprofile_params)

    respond_to do |format|
      if @uprofile.save
        format.html { redirect_to @uprofile, notice: 'Uprofile was successfully created.' }
        format.json { render :show, status: :created, location: @uprofile }
      else
        format.html { render :new }
        format.json { render json: @uprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uprofiles/1
  # PATCH/PUT /uprofiles/1.json
  def update
    respond_to do |format|
      if @uprofile.update(uprofile_params)
        format.html { redirect_to @uprofile, notice: 'Uprofile was successfully updated.' }
        format.json { render :show, status: :ok, location: @uprofile }
      else
        format.html { render :edit }
        format.json { render json: @uprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uprofiles/1
  # DELETE /uprofiles/1.json
  def destroy
    @uprofile.destroy
    respond_to do |format|
      format.html { redirect_to uprofiles_url, notice: 'Uprofile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uprofile
      @uprofile = Uprofile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uprofile_params
      params.require(:uprofile).permit(:firstname, :lastname, :manageremail, :leavebalance, :leaveentitlement, :user_id)
    end
end

app/helpers/uprofiles_helper.rb
module UprofilesHelper
end

app/views/uprofiles/_form.html.1.erb
<%= form_with(model: uprofile, local: true) do |form| %>
  <% if uprofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uprofile.errors.count, "error") %> prohibited this uprofile from being saved:</h2>

      <ul>
      <% uprofile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :manageremail %>
    <%= form.text_field :manageremail %>
  </div>

  <div class="field">
    <%= form.label :leavebalance %>
    <%= form.number_field :leavebalance %>
  </div>

  <div class="field">
    <%= form.label :leaveentitlement %>
    <%= form.number_field :leaveentitlement %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uprofiles/_form.html.erb
<%= form_for(@uprofile) do |f| %>
  <% if @uprofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uprofile.errors.count, "error") %> prohibited this Profile from being saved:</h2>
      <ul>
      <% @uprofile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :First_Name %><br>
    <%= f.text_field :firstname, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Last_Name %><br>
    <%= f.text_field :lastname, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Manager_Email %><br>
    <%= f.text_field :manageremail, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Leave_Balance %><br>
    <%= f.number_field :leavebalance, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Leave_Entitlement %><br>
    <%= f.number_field :leaveentitlement, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :User_ID %><br>
    <%= f.text_field :user_id, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Create Profile', class: "btn btn-primary" %>
  </div>
<% end %>
<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/uprofiles/edit.html.erb
<h1>Editing User Profile</h1>

<%= render 'form', uprofile: @uprofile %>

<%= link_to 'Show', @uprofile %> |
<%= link_to 'Back', uprofiles_path %>

app/views/uprofiles/index.html.1.erb
<p id="notice"><%= notice %></p>

<h1>Uprofiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Manageremail</th>
      <th>Leavebalance</th>
      <th>Leaveentitlement</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uprofiles.each do |uprofile| %>
      <tr>
        <td><%= uprofile.firstname %></td>
        <td><%= uprofile.lastname %></td>
        <td><%= uprofile.manageremail %></td>
        <td><%= uprofile.leavebalance %></td>
        <td><%= uprofile.leaveentitlement %></td>
        <td><%= uprofile.user %></td>
        <td><%= link_to 'Show', uprofile %></td>
        <td><%= link_to 'Edit', edit_uprofile_path(uprofile) %></td>
        <td><%= link_to 'Destroy', uprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uprofile', new_uprofile_path %>

app/views/uprofiles/index.html.erb
<%= flash_messages %>
<h2>User Profile List</h2>

<div class="leaverequest-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-1">First_Name</th>
        <th class="col-md-1">Last_name</th>
        <th class="col-md-1">Manager_Email</th>
     <th class="col-md-4">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @uprofiles.each do |uprofile| %>
        <tr>
         <td class="col-md-1"><%= uprofile.firstname %></td>
         <td class="col-md-1"><%= uprofile.lastname %></td>
         <td class="col-md-1"><%= uprofile.manageremail %></td>
         <td class="col-md-4">
            <%= link_to 'Show', uprofile_path(uprofile), class: "btn btn-info" %>
            <%= link_to 'Update Profile', edit_uprofile_path(uprofile), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', uprofile_path(uprofile), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </td>
     </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/uprofiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form', uprofile: @uprofile %>

<%= link_to 'Back', uprofiles_path %>

app/views/uprofiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @uprofile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @uprofile.lastname %>
</p>

<p>
  <strong>Manageremail:</strong>
  <%= @uprofile.manageremail %>
</p>

<p>
  <strong>Leavebalance:</strong>
  <%= @uprofile.leavebalance %>
</p>

<p>
  <strong>Leaveentitlement:</strong>
  <%= @uprofile.leaveentitlement %>
</p>

<p>
  <strong>User:</strong>
  <%= @uprofile.user %>
</p>

<%= link_to 'Edit', edit_uprofile_path(@uprofile) %> |
<%= link_to 'Back', uprofiles_path %>