config/routes.rb
Rails.application.routes.draw do
  resources :leaverequests
  get 'users/index'
  resources :clockeds
  resources :uprofiles
  root 'dashboard#index'
  resources :clocks
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/clocked.rb
class Clocked < ApplicationRecord
   belongs_to :user
  
  geocoded_by :location_in,
   :latitude => :latitude, :longitude => :longitude, :address => :address
 after_validation :geocode
 
 reverse_geocoded_by :latitude, :longitude,
   :address => :address
 after_validation :reverse_geocode
end

app/controllers/clockeds_controller.rb
class ClockedsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_clocked, only: [:show, :edit, :update, :destroy]

  # GET /clockeds
  # GET /clockeds.json
  def index
    @clockeds = Clocked.order("created_at desc").where(user_id: current_user.clocked_ids + [current_user.id])
  end

  # GET /clockeds/1
  # GET /clockeds/1.json
  def show
  end

  # GET /clockeds/new
  def new
    @clocked = Clocked.new
    @clocked.user_id = current_user.id
    @clocked.location_in = current_user.current_sign_in_ip
    @clocked.crddate = DateTime.now
    @clocked.crdtime = DateTime.now
    @clocked.edittimenw = Time.now
    
  end

  # GET /clockeds/1/edit
  def edit
    @clocked.location_out = current_user.current_sign_in_ip
    @clocked.eddate = DateTime.now
    @clocked.edittimenw = Time.now
    @clocked.updatedt = DateTime.now
    @clocked.hour = (@clocked.updatedt - @clocked.created_at) / 1.hours
  end

  # POST /clockeds
  # POST /clockeds.json
  def create
    @clocked = Clocked.new(clocked_params)

    respond_to do |format|
      if @clocked.save
        format.html { redirect_to @clocked, notice: 'Clocked was successfully created.' }
        format.json { render :show, status: :created, location: @clocked }
      else
        format.html { render :new }
        format.json { render json: @clocked.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clockeds/1
  # PATCH/PUT /clockeds/1.json
  def update
    respond_to do |format|
      if @clocked.update(clocked_params)
        format.html { redirect_to @clocked, notice: 'Clocked was successfully updated.' }
        format.json { render :show, status: :ok, location: @clocked }
      else
        format.html { render :edit }
        format.json { render json: @clocked.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clockeds/1
  # DELETE /clockeds/1.json
  def destroy
    @clocked.destroy
    respond_to do |format|
      format.html { redirect_to clockeds_url, notice: 'Clocked was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clocked
      @clocked = Clocked.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clocked_params
      params.require(:clocked).permit(:hour, :location_in, :location_out, :crddate, :crdtime, :address, :latitude, :longitude, :user_id)
    end
end

app/helpers/clockeds_helper.rb
module ClockedsHelper
end

app/views/clockeds/_form.html.1.erb
<%= form_with(model: clocked, local: true) do |form| %>
  <% if clocked.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clocked.errors.count, "error") %> prohibited this clocked from being saved:</h2>

      <ul>
      <% clocked.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hour %>
    <%= form.number_field :hour %>
  </div>

  <div class="field">
    <%= form.label :location_in %>
    <%= form.text_field :location_in %>
  </div>

  <div class="field">
    <%= form.label :location_out %>
    <%= form.text_field :location_out %>
  </div>

  <div class="field">
    <%= form.label :crddate %>
    <%= form.date_select :crddate %>
  </div>

  <div class="field">
    <%= form.label :crdtime %>
    <%= form.time_select :crdtime %>
  </div>
  
  <div class="field">
    <%= form.label :eddate %>
    <%= form.date_select :eddate %>
  </div>

  <div class="field">
    <%= form.label :edtime %>
    <%= form.time_select :edtime %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  
  <div class="field">
    <%= form.label :updatedt %>
    <%= form.datetime_select :updatedt %>
  </div>
  
  

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clockeds/_form.html.erb
<%= form_for(@clocked) do |f| %>
  <% if @clocked.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clocked.errors.count, "error") %> prohibited this clock from being saved:</h2>
      <ul>
      <% @clocked.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :hour %><br>
    <%= f.text_field :hour, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :location_out, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :longitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :latitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Time_In %><br>
    <%= f.time_select :crdtime, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Time_Out %><br>
    <%= f.time_select :edittimenw, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :user_id, class: "form-control" %>
  </div>
  </div>
  

  <div class="actions">
    <%= f.submit 'Clock Out', class: "btn btn-primary" %>
  </div>
<% end %>
<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/clockeds/edit.html.erb
<h1>Clock Out</h1>

<%= render 'form', clocked: @clocked %>

<%= link_to 'Show', @clocked %> |
<%= link_to 'Back', clockeds_path %>

app/views/clockeds/index.html.erb
<%= flash_messages %>
<h2>Your Clock History</h2>

<div class="clocked-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-1">Hour</th>
        <th class="col-md-2">Date</th>
        <th class="col-md-1">Time In</th>
        <th class="col-md-1">Time Out</th>
        <th class="col-md-2">Address In</th>
        <th class="col-md-2">Address Out</th>
     <th class="col-md-6">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @clockeds.each do |clocked| %>
        <tr>
         <td class="col-md-1"><%= clocked.hour %></td>
         <td class="col-md-2"><%= clocked.crddate %></td>
         <td class="col-md-1"><%= clocked.crdtime.strftime("%I:%M %P") %></td>
         <td class="col-md-1"><%= clocked.updated_at.strftime("%I:%M %P") %></td>
         <td class="col-md-2"><%= clocked.address %></td>
         <td class="col-md-2"><%= clocked.address %></td>
         <td class="col-md-6">
            <%= link_to 'Show', clocked_path(clocked), class: "btn btn-info" %>
            <%= link_to 'Clock out', edit_clocked_path(clocked), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', clocked_path(clocked), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </td>
     </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Clock', new_clocked_path, class: "btn btn-primary" %>

app/views/clockeds/new.html.erb
<h2>New Clock</h2>
<%= form_for(@clocked) do |f| %> 
<% if @clocked.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clocked.errors.count, "error") %> prohibited this clock from being saved:</h2>
      <ul>
      <% @clocked.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :location_in %><br>
    <%= f.text_field :location_in, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :longitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :latitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  </div>
   <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Date %><br>
    <%= f.date_select :crddate, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Time_In %><br>
    <%= f.time_select :crdtime, class: "form-control" %>
  </div>
  </div>
    <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :edittimenw, class: "form-control" %>
  </div>
  </div>
 <div class="row">
  <div class="form-group col-md-4">
    <%= f.hidden_field :user_id, class: "form-control"  %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Clock In", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/clockeds/new.oldhtml.erb
<h2>New Clock</h2>

<%= render 'form' %>

<%= link_to "Back", clockeds_path, class: "btn btn-default" %>

app/views/clockeds/show.html.erb
<%= flash_messages %>
<header><h1 class="display-4"><%= @clocked.user.try(:email) %></h1></header>

<p>Address: <%= @clocked.address %></p>
<p>Coordinates: <%= @clocked.latitude %> <%= @clocked.longitude %></p>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@clocked.latitude},#{@clocked.longitude}&markers=#{@clocked.latitude},#{@clocked.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
              class: 'img-fluid img-rounded', alt: "#{@clocked.id} on the map"%>


<%= link_to "Back", clockeds_path, class: "btn btn-default" %>