config/routes.rb
Rails.application.routes.draw do
  resources :leaverequests
  get 'users/index'
  resources :clockeds
  resources :uprofiles
  root 'dashboard#index'
  resources :clocks
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/clock.rb
class Clock < ApplicationRecord
  belongs_to :user
  
  geocoded_by :geolocation_in,
   :latitude => :latitude, :longitude => :longitude, :address => :address
 after_validation :geocode
 
 reverse_geocoded_by :latitude, :longitude,
   :address => :address
 after_validation :reverse_geocode
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_clock, only: [:show, :edit, :update, :destroy]
  
  
  # GET /clocks
  # GET /clocks.json
  def index
    @clocks = Clock.all
    @clocks = current_user.clocks 
    #@clocks = Clock.order("created_at desc").where(user_id: current_user.clock_ids + [current_user.id])
  end
  # GET /clocks/1
  # GET /clocks/1.json
  def show
  end

  # GET /clocks/new
  def new
    @clock = Clock.new
    @clock.user_id = current_user.id
    @clock.geolocation_in = current_user.current_sign_in_ip
    @clock.crdt = DateTime.now
    
  end

  # GET /clocks/1/edit
  def edit
    #@clock.hours = (@clock.created_at - DateTime.now) / 1.hours
    @clock.hours = (@clock.created_at - @clock.updated_at) / 1.hours
    @clock.geolocation_out = current_user.current_sign_in_ip
  end

  # POST /clocks
  # POST /clocks.json
  def create
    @clock = Clock.new(clock_params)
    @clock.user = current_user
    @clock.crdt = DateTime.now
    respond_to do |format|
      if @clock.save
        format.html { redirect_to @clock, notice: 'Clock was successfully created.' }
        format.json { render :show, status: :created, location: @clock }
      else
        format.html { render :new }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocks/1
  # PATCH/PUT /clocks/1.json
  
  def update
    respond_to do |format|
      
      if @clock.update(clock_params)
        format.html { redirect_to @clock, notice: 'Clock was successfully updated.' }
        format.json { render :show, status: :ok, location: @clock }
      else
        format.html { render :edit }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocks/1
  # DELETE /clocks/1.json
  def destroy
    @clock.destroy
    respond_to do |format|
      format.html { redirect_to clocks_url, notice: 'Clock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clock
      @clock = Clock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clock_params
      params.require(:clock).permit(:hours, :geolocation_in, :geolocation_out, :user_id)
    end
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/_form.html.erb
<%= form_for(@clock) do |f| %>
  <% if @clock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clock.errors.count, "error") %> prohibited this clock from being saved:</h2>
      <ul>
      <% @clock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :hours %><br>
    <%= f.text_field :hours, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :created %><br>
    <%= f.text_field :crdt, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :geolocation_in %><br>
    <%= f.text_field :geolocation_in, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :updated_at %><br>
    <%= f.text_field :updated_at, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>
<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/clocks/edit.html.erb
<h2>Editing Clock</h2>

<%= render 'form' %>

<%= link_to 'Show', @clock, class: "btn btn-warning" %>
<%= link_to 'Back', clocks_path, class: "btn btn-default" %>

app/views/clocks/editnewold.html.erb
<h2>Clock Out</h2>
<%= form_for(@clock) do |f| %> 
<% if @clock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clock.errors.count, "error") %> prohibited this clock from being saved:</h2>
      <ul>
      <% @clock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Hours %><br>
    <%= f.text_field :hours, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Clock_In %><br>
    <%= f.text_field :created_at, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Clock_Out %><br>
    <%= f.text_field :updated_at, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :geolocation_in %><br>
    <%= f.text_field :geolocation_in, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :geolocation_out %><br>
    <%= f.text_field :geolocation_out, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Clock Out", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/clocks/indeoldx.html.erb
<%= flash_messages %>
<h2>Your Clock History</h2>
<div class="clock-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-2">Hours</th>
     <th class="col-md-2">GeolocationIn</th>
     <th class="col-md-4">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @clocks.each do |clock| %>
        <tr>
         <td class="col-md-2"><%= clock.hours %></td>
         <td class="col-md-2"><%= clock.geolocation_in %></td>
         <td class="col-md-4">
            <%= link_to 'Show', clock_path(clock), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_clock_path(clock), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', clock_path(clock), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </td>
     </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Clock', new_clock_path, class: "btn btn-primary" %>

app/views/clocks/index.html.erb
<%= flash_messages %>
<h2>Clocks List</h2>

<div class="clock-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-1">Hours</th>
        <th class="col-md-1">Date</th>
        <th class="col-md-1">Time In</th>
        <th class="col-md-1">Time Out</th>
        <th class="col-md-1">location In</th>
        <th class="col-md-1">location Out</th>
     <th class="col-md-4">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @clocks.each do |clock| %>
        <tr>
         <td class="col-md-1"><%= clock.hours %></td>
         <td class="col-md-1"><%= clock.created_at.to_date %></td>
         <td class="col-md-1"><%= clock.created_at.strftime("%I:%M %P") %></td>
         <td class="col-md-1"><%= clock.geolocation_in %></td>
         <td class="col-md-1"><%= clock.geolocation_out %></td>
         <td class="col-md-4">
            <%= link_to 'Show', clock_path(clock), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_clock_path(clock), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', clock_path(clock), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </td>
     </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Clock', new_clock_path, class: "btn btn-primary" %>

app/views/clocks/neoldoldw.html.erb
<h2>New Clock</h2>
<%= form_for(@clock) do |f| %> 
<% if @clock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clock.errors.count, "error") %> prohibited this clock from being saved:</h2>
      <ul>
      <% @clock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :created %><br>
    <%= f.text_field :crdt, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :geolocation_in %><br>
    <%= f.text_field :geolocation_in, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Clock In", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/clocks/new.html.erb
<h2>New Clock</h2>

<%= render 'form' %>

<%= link_to "Back", clocks_path, class: "btn btn-default" %>

app/views/clocks/show.html.erb
<%= flash_messages %>
<header><h1 class="display-4"><%= @clock.user.try(:email) %></h1></header>

<p>Address: <%= @clock.address %></p>
<p>Coordinates: <%= @clock.latitude %> <%= @clock.longitude %></p>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@clock.latitude},#{@clock.longitude}&markers=#{@clock.latitude},#{@clock.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
              class: 'img-fluid img-rounded', alt: "#{@clock.id} on the map"%>

<%= link_to 'Edit', edit_clock_path(@clock), class: "btn btn-warning" %>
<%= link_to "Back", clocks_path, class: "btn btn-default" %>