config/routes.rb
Rails.application.routes.draw do
  resources :leaverequests
  get 'users/index'
  resources :clockeds
  resources :uprofiles
  root 'dashboard#index'
  resources :clocks
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.1.erb
<!DOCTYPE html>
<html>
<head>
  <title>WLCT</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsOuKeyn47AjfnjlFW5hj9ouA9re6Rahg&callback=initMap"
                                         async defer></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">Dashboard</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clocks <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Clock History", clockeds_path %></li>
        <li><%= link_to "New Clock", new_clocked_path %></li>
        <li><%= link_to "Leave Request History", leaverequests_path %></li>
        <li><%= link_to "New Leave Request", new_leaverequest_path %></li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Options <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
      <li><%= link_to "Edit Sign Up", edit_user_registration_path %></li>
      <li><%= link_to "List Users", users_path %></li>
      <li><%= link_to "List User Profiles", uprofiles_path %></li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </li>
</ul>
</div>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.2.erb
<!DOCTYPE html>
<html>
<head>
  <title>WLCT</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsOuKeyn47AjfnjlFW5hj9ouA9re6Rahg&callback=initMap"
                                         async defer></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">Dashboard</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clocks <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Clock History", clockeds_path %></li>
        <li><%= link_to "New Clock", new_clocked_path %></li>
        <li><%= link_to "Leave Request History", leaverequests_path %></li>
        <li><%= link_to "New Leave Request", new_leaverequest_path %></li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Options <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
      <li><%= link_to "Edit Sign Up", edit_user_registration_path %></li>
      <li><%= link_to "List Users", users_path %></li>
      <li><%= link_to "List User Profiles", uprofiles_path %></li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </li>
</ul>
</div>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WLCT</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsOuKeyn47AjfnjlFW5hj9ouA9re6Rahg&callback=initMap"
                                         async defer></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">Dashboard</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clock <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Clock History", clockeds_path %></li>
        <li><%= link_to "New Clock", new_clocked_path %></li>
      </ul>
    </li>
  </ul>
    <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Leave Requests <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Leave Request History", leaverequests_path %></li>
        <li><%= link_to "New Leave Request", new_leaverequest_path %></li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Options <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
      <li><%= link_to "Edit Sign Up", edit_user_registration_path %></li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </li>
</ul>
<ul class="nav navbar-nav navbar-left">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
      <li><%= link_to "List Users", users_path %></li>
      <li><%= link_to "List User Profiles", uprofiles_path %></li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </li>

</div>
      </div>
    </div>
  </nav>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
</body>
</html>